spring:
  application:
    name: bank_system

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  banner:
    location: banner/banner-dev.txt

springdoc:
  swagger-ui:
    path: /docs
    enabled: true
    doc-expansion: none
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
    enabled: true

minio:
  url: http://localhost:9000
  access-key: user
  secret-key: password
  bucket-name: bank-system-bucket